name: 'confluent-kafka-dotnet build pipeline'

env:
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

on:
  push:
  pull_request:

jobs:

  integration-tests:
    name: 'Integration tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

  linux-build:
    name: 'Linux x64'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build and test
        run: |
          dotnet restore
          make build
          make test

  osx-build:
    name: 'OSX x64'
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Set ulimit
        run: ulimit -n 1024
      - name: Build and test
        run: |
          dotnet restore
          make build
          make test

  windows-build:
    name: 'Windows x64'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.403'
      - name: Build and test
        run: |
          dotnet restore
          dotnet test -c $env:CONFIGURATION test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj

  windows-artifacts:
    name: 'Windows Artifacts'
    needs: windows-build
    runs-on: windows-latest
    steps:
      
      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.403'
      - name: Build and create packages
        run: |
          dotnet restore
          dotnet build Confluent.Kafka.sln -c $env:CONFIGURATION

          # Different packaging for tagged vs untagged builds
          if ($env:GITHUB_REF -match '^refs/tags/') {
            $suffix = "gr.$env:GITHUB_RUN_NUMBER"
            $vsuffix = "--version-suffix"
          } else {
            $suffix = "ci-$env:GITHUB_RUN_ID"
            $vsuffix = "--version-suffix"
          }

          dotnet pack src/Confluent.Kafka/Confluent.Kafka.csproj --output artifacts -c $env:CONFIGURATION $vsuffix $suffix 

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: artifacts/
